name: Semantic Release
on:
  push:
    branches:
    - master
    
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Semantic release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 17
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_notes: ${{ steps.semantic.outputs.new_release_notes }}